version: "3.7"
services:
  develop:
    container_name: torch2trt-test
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    shm_size: "4gb"
    tty: true
    volumes:
      - .:/home/dev/convert-test-torch2trt
