defaults:
  - _self_
  - hydra: default
  - u2net@salient: salient
  - u2net@portrait: portrait
  - override hydra/job_logging: custom

general:
  seed: 0
  image_path: ../images/bird.jpg
  norm_hist: False
  save_masked_img: False
